# Generated by Django 3.2.7 on 2021-09-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.EmailField(default=2, max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
