# Generated by Django 3.2.7 on 2021-09-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApi', '0002_auto_20210919_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='designation',
            field=models.CharField(max_length=70),
        ),
    ]
